services:
  bazar:
    image: moifort/bazar:latest
    container_name: bazar
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: "3000"
      NITRO_API_TOKEN: ${NITRO_API_TOKEN}
      NITRO_GOOGLE_API_KEY: ${NITRO_GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/.data
