query ItemDetail($id: ItemId!) {
  item(id: $id) {
    id
    name
    description
    category
    quantity
    addedBy
    personalNotes
    purchaseDate
    purchaseLocation
    createdAt
    updatedAt
    location {
      fullPath
      placeId
      placeName
      roomId
      roomName
      zoneId
      zoneName
      storageId
      storageName
    }
    reminders {
      id
      title
      notes
      dueDate
      frequency
      customIntervalDays
      createdAt
      updatedAt
    }
  }
}
